=== alainmevel/CB_examples/Configuration/xsd/network_io_patterns.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="NetworkIOCodeGenerationConfiguration">
		<xs:annotation>
			<xs:documentation>Contains patterns declaration for IO code generation</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="ENUM"></xs:element>
				<xs:element maxOccurs="unbounded" ref="Network"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ENUM">
		<xs:annotation>
			<xs:documentation>Declaration of an enumerated type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="ITEM"></xs:element>
			</xs:sequence>
			<xs:attribute name="NAME" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="ITEM" type="xs:string">
		<xs:annotation>
			<xs:documentation>An item of an enumeration</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="Network">
		<xs:annotation>
			<xs:documentation>Nertwork variables list</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="NetworkVariable"></xs:element>
				<xs:element minOccurs="1" maxOccurs="1" ref="NetworkIOPatterns"></xs:element>
			</xs:sequence>
			<xs:attribute name="PROTOCOL" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="NetworkVariable">
		<xs:annotation>
			<xs:documentation>Contains the label for one language</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" ref="Performer"></xs:element>
			</xs:sequence>
			<xs:attribute name="Tag" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="Performer">
		<xs:annotation>
			<xs:documentation>Data accessor</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="Receiver" type="receivers" use="required"></xs:attribute>
			<xs:attribute name="Selector" type="selectors" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="NetworkIOPatterns">
		<xs:annotation>
			<xs:documentation>Definition of a property</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" ref="NetworkInputPattern"></xs:element>
				<xs:element minOccurs="1" maxOccurs="1" ref="NetworkOutputPattern"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="NetworkInputPattern" type="xs:string">
		<xs:annotation>
			<xs:documentation>Contains the pattern for input functions</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="NetworkOutputPattern" type="xs:string">
		<xs:annotation>
			<xs:documentation>Contains the pattern for output functions</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:simpleType name="receivers">
		<xs:restriction base="xsd:string">
			<xs:enumeration value="currentIO"/>
			<xs:enumeration value="currentNetwork"/>
			<xs:enumeration value="currentFrame"/>
			<xs:enumeration value="currentSignal"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="selectors">
			<xs:restriction base="xsd:string">
				<xs:enumeration value="name"/>
				<xs:enumeration value="identifier"/>
				<xs:enumeration value="index"/>
				<xs:enumeration value="basicType"/>
				<xs:enumeration value="type"/>
				<xs:enumeration value="size"/>				
				<xs:enumeration value="protocol"/>
				<xs:enumeration value="bit"/>
				<xs:enumeration value="byte"/>
				<xs:enumeration value="startBit"/>
				<xs:enumeration value="length"/>
				<xs:enumeration value="indian"/>
				<xs:enumeration value="isSigned"/>
				<xs:enumeration value="resolution"/>
				<xs:enumeration value="offset"/>
				<xs:enumeration value="minValue"/>
				<xs:enumeration value="maxValue"/>				
			</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== alainmevel/CB_examples/Configuration/network_io_patterns.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generator: controlbuild -->

<NetworkIOCodeGenerationConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:xsd/network_io_patterns.xsd">
	<Network PROTOCOL="ETH">
		<NetworkVariable Tag="$1">
			<Performer Receiver="currentIO" Selector="type" />
		</NetworkVariable>
		<NetworkVariable Tag="$2">
			<Performer Receiver="currentIO" Selector="index" />
		</NetworkVariable>
		<NetworkVariable Tag="$3">
			<Performer Receiver="currentNetwork" Selector="protocol" />
		</NetworkVariable>
		<NetworkVariable Tag="$4">
			<Performer Receiver="currentFrame" Selector="name" />
		</NetworkVariable>
		<NetworkVariable Tag="$5">
			<Performer Receiver="currentSignal" Selector="startBit" />
		</NetworkVariable>
		<NetworkVariable Tag="$6">
			<Performer Receiver="currentIO" Selector="name" />
		</NetworkVariable>
		<NetworkVariable Tag="$7">
			<Performer Receiver="currentSignal" Selector="name" />
		</NetworkVariable>
		<NetworkIOPatterns>
			<NetworkInputPattern>/* $6 */ P_$1(memHeader, $2)-&gt;CB_current_value = /* $7 */ $3_Extract_$1(&quot;$4&quot;, $5);</NetworkInputPattern>
			<NetworkOutputPattern>/* $7 */ $3_Compact_$1(/* $6  */ P_$1(memHeader, $2)-&gt;CB_current_value, &quot;$4&quot;, $5);</NetworkOutputPattern>
		</NetworkIOPatterns>
	</Network>
	<Network PROTOCOL="CAN">
		<NetworkVariable Tag="$1">
			<Performer Receiver="currentIO" Selector="type" />
		</NetworkVariable>
		<NetworkVariable Tag="$2">
			<Performer Receiver="currentIO" Selector="index" />
		</NetworkVariable>
		<NetworkVariable Tag="$3">
			<Performer Receiver="currentNetwork" Selector="protocol" />
		</NetworkVariable>
		<NetworkVariable Tag="$4">
			<Performer Receiver="currentFrame" Selector="identifier" />
		</NetworkVariable>
		<NetworkVariable Tag="$5">
			<Performer Receiver="currentSignal" Selector="startBit" />
		</NetworkVariable>
		<NetworkVariable Tag="$6">
			<Performer Receiver="currentIO" Selector="name" />
		</NetworkVariable>
		<NetworkVariable Tag="$7">
			<Performer Receiver="currentSignal" Selector="name" />
		</NetworkVariable>
		<NetworkIOPatterns>
			<NetworkInputPattern>/* $6 */ P_$1(memHeader, $2)-&gt;CB_current_value = /* $7 */ $3_Extract_$1($4, $5);</NetworkInputPattern>
			<NetworkOutputPattern>/* $7 */ $3_Compact_$1(/* $6  */ P_$1(memHeader, $2)-&gt;CB_current_value, $4, $5);</NetworkOutputPattern>
		</NetworkIOPatterns>
	</Network>
</NetworkIOCodeGenerationConfiguration>
